### ISSUE TITLE
HTTP Error.

### ISSUE THREAD

**Issue by RoelvandenBerg** [RoelvandenBerg/groundwater_timenet#2]
```python
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/suds/transport/http.py", line 80, in send
    fp = self.u2open(u2request)
  File "/usr/lib/python3/dist-packages/suds/transport/http.py", line 127, in u2open
    return url.open(u2request, timeout=tm)
  File "/usr/lib/python3.5/urllib/request.py", line 472, in open
    response = meth(req, response)
  File "/usr/lib/python3.5/urllib/request.py", line 582, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.5/urllib/request.py", line 510, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 444, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 590, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 503: Service Temporarily Unavailable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/suds/client.py", line 747, in send
    reply = self.options.transport.send(request)
  File "/usr/lib/python3/dist-packages/suds/transport/https.py", line 66, in send
    return HttpTransport.send(self, request)
  File "/usr/lib/python3/dist-packages/suds/transport/http.py", line 90, in send
    raise TransportError(e.msg, e.code, e.fp)
suds.transport.TransportError: Service Temporarily Unavailable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "groundwater_timenet/dino.py", line 302, in <module>
    download_hdf5(skip, FILENAME_BASE)
  File "groundwater_timenet/dino.py", line 226, in download_hdf5
    for metadata, well_data in grid_cell:
  File "groundwater_timenet/dino.py", line 190, in load_dino_grid_cell
    data = load_station_data(well)
  File "groundwater_timenet/dino.py", line 102, in load_station_data
    UNIT='SFL'
  File "/usr/lib/python3/dist-packages/suds/client.py", line 566, in __call__
    return client.invoke(args, kwargs)
  File "/usr/lib/python3/dist-packages/suds/client.py", line 705, in invoke
    result = self.send(soapenv)
  File "/usr/lib/python3/dist-packages/suds/client.py", line 752, in send
    return self.process_reply(content, e.httpcode, tostr(e))
  File "/usr/lib/python3/dist-packages/suds/client.py", line 819, in process_reply
    raise Exception((status, description))
Exception: (503, 'Service Temporarily Unavailable')
```

**Comment by RoelvandenBerg** [comment]
The uncomitted temporary fix doesn't work as yet.

```python
#2017-06-10 08:07:12,842 - __main__ - ERROR - Suds client is unavailable for well B07D0451, waiting for 10 minutes, breaking query period in two
Traceback (most recent call last):
  File "groundwater_timenet/dino.py", line 112, in load_station_data
    UNIT='SFL'
  File "/usr/lib/python3/dist-packages/suds/client.py", line 566, in __call__
    return client.invoke(args, kwargs)
  File "/usr/lib/python3/dist-packages/suds/client.py", line 705, in invoke
    result = self.send(soapenv)
  File "/usr/lib/python3/dist-packages/suds/client.py", line 747, in send
    reply = self.options.transport.send(request)
  File "/usr/lib/python3/dist-packages/suds/transport/https.py", line 66, in send
    return HttpTransport.send(self, request)
  File "/usr/lib/python3/dist-packages/suds/transport/http.py", line 80, in send
    fp = self.u2open(u2request)
  File "/usr/lib/python3/dist-packages/suds/transport/http.py", line 127, in u2open
    return url.open(u2request, timeout=tm)
  File "/usr/lib/python3.5/urllib/request.py", line 466, in open
    response = self._open(req, data)
  File "/usr/lib/python3.5/urllib/request.py", line 484, in _open
    '_open', req)
  File "/usr/lib/python3.5/urllib/request.py", line 444, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 1282, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "/usr/lib/python3.5/urllib/request.py", line 1257, in do_open
    r = h.getresponse()
  File "/usr/lib/python3.5/http/client.py", line 1197, in getresponse
    response.begin()
  File "/usr/lib/python3.5/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.5/http/client.py", line 258, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.5/socket.py", line 575, in readinto
    return self._sock.recv_into(b)
socket.timeout: timed out
#2017-06-10 08:18:43,082 - __main__ - ERROR - Suds client is unavailable for well B07D0451, waiting for 10 minutes, breaking query period in two
Traceback (most recent call last):
  File "groundwater_timenet/dino.py", line 112, in load_station_data
    UNIT='SFL'
  File "/usr/lib/python3/dist-packages/suds/client.py", line 566, in __call__
    return client.invoke(args, kwargs)
  File "/usr/lib/python3/dist-packages/suds/client.py", line 705, in invoke
    result = self.send(soapenv)
  File "/usr/lib/python3/dist-packages/suds/client.py", line 747, in send
    reply = self.options.transport.send(request)
  File "/usr/lib/python3/dist-packages/suds/transport/https.py", line 66, in send
    return HttpTransport.send(self, request)
  File "/usr/lib/python3/dist-packages/suds/transport/http.py", line 80, in send
    fp = self.u2open(u2request)
  File "/usr/lib/python3/dist-packages/suds/transport/http.py", line 127, in u2open
    return url.open(u2request, timeout=tm)
  File "/usr/lib/python3.5/urllib/request.py", line 466, in open
    response = self._open(req, data)
  File "/usr/lib/python3.5/urllib/request.py", line 484, in _open
    '_open', req)
  File "/usr/lib/python3.5/urllib/request.py", line 444, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 1282, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "/usr/lib/python3.5/urllib/request.py", line 1257, in do_open
    r = h.getresponse()
  File "/usr/lib/python3.5/http/client.py", line 1197, in getresponse
    response.begin()
  File "/usr/lib/python3.5/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.5/http/client.py", line 258, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.5/socket.py", line 575, in readinto
    return self._sock.recv_into(b)
socket.timeout: timed out
#2017-06-10 08:30:13,335 - __main__ - ERROR - Suds client is unavailable for well B07D0451, waiting for 10 minutes, breaking query period in two
Traceback (most recent call last):
  File "groundwater_timenet/dino.py", line 112, in load_station_data
    UNIT='SFL'
  File "/usr/lib/python3/dist-packages/suds/client.py", line 566, in __call__
    return client.invoke(args, kwargs)
  File "/usr/lib/python3/dist-packages/suds/client.py", line 705, in invoke
    result = self.send(soapenv)
  File "/usr/lib/python3/dist-packages/suds/client.py", line 747, in send
    reply = self.options.transport.send(request)
  File "/usr/lib/python3/dist-packages/suds/transport/https.py", line 66, in send
    return HttpTransport.send(self, request)
  File "/usr/lib/python3/dist-packages/suds/transport/http.py", line 80, in send
    fp = self.u2open(u2request)
  File "/usr/lib/python3/dist-packages/suds/transport/http.py", line 127, in u2open
    return url.open(u2request, timeout=tm)
  File "/usr/lib/python3.5/urllib/request.py", line 466, in open
    response = self._open(req, data)
  File "/usr/lib/python3.5/urllib/request.py", line 484, in _open
    '_open', req)
  File "/usr/lib/python3.5/urllib/request.py", line 444, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 1282, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "/usr/lib/python3.5/urllib/request.py", line 1257, in do_open
    r = h.getresponse()
  File "/usr/lib/python3.5/http/client.py", line 1197, in getresponse
    response.begin()
  File "/usr/lib/python3.5/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.5/http/client.py", line 258, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.5/socket.py", line 575, in readinto
    return self._sock.recv_into(b)
socket.timeout: timed out
#2017-06-10 08:41:43,574 - __main__ - ERROR - Suds client is unavailable for well B07D0451, waiting for 10 minutes, breaking query period in two
Traceback (most recent call last):
  File "groundwater_timenet/dino.py", line 112, in load_station_data
    UNIT='SFL'
  File "/usr/lib/python3/dist-packages/suds/client.py", line 566, in __call__
    return client.invoke(args, kwargs)
  File "/usr/lib/python3/dist-packages/suds/client.py", line 705, in invoke
    result = self.send(soapenv)
  File "/usr/lib/python3/dist-packages/suds/client.py", line 747, in send
    reply = self.options.transport.send(request)
  File "/usr/lib/python3/dist-packages/suds/transport/https.py", line 66, in send
    return HttpTransport.send(self, request)
  File "/usr/lib/python3/dist-packages/suds/transport/http.py", line 80, in send
    fp = self.u2open(u2request)
  File "/usr/lib/python3/dist-packages/suds/transport/http.py", line 127, in u2open
    return url.open(u2request, timeout=tm)
  File "/usr/lib/python3.5/urllib/request.py", line 466, in open
    response = self._open(req, data)
  File "/usr/lib/python3.5/urllib/request.py", line 484, in _open
    '_open', req)
  File "/usr/lib/python3.5/urllib/request.py", line 444, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 1282, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "/usr/lib/python3.5/urllib/request.py", line 1257, in do_open
    r = h.getresponse()
  File "/usr/lib/python3.5/http/client.py", line 1197, in getresponse
    response.begin()
  File "/usr/lib/python3.5/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.5/http/client.py", line 258, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.5/socket.py", line 575, in readinto
    return self._sock.recv_into(b)
socket.timeout: timed out
#2017-06-10 08:56:27,230 - __main__ - INFO - Got Feature: ['B07D0451', 001, 235405, 582465, '2002-10-25', '2016-11-10', 63.29, 13.24, 64.29, 14.24, -62.94, -12.89, '', ''], size: 52713
#2017-06-10 08:56:27,671 - __main__ - INFO - Got Feature: ['B07D0451', 002, 235405, 582465, '2002-10-25', '2016-11-10', 63.29, 13.24, 64.29, 14.24, -62.94, -12.89, '', ''], size: 52859
#2017-06-10 08:56:27,877 - __main__ - INFO - Got Feature: ['B07D0451', 003, 235405, 582465, '2002-10-25', '2016-11-10', 63.29, 13.24, 64.29, 14.24, -62.94, -12.89, '', ''], size: 50231
#2017-06-10 08:56:28,090 - __main__ - INFO - Got Feature: ['B07D0451', 004, 235405, 582465, '2002-10-25', '2016-11-10', 63.29, 13.24, 64.29, 14.24, -62.94, -12.89, '', ''], size: 52858
#2017-06-10 08:56:28,297 - __main__ - INFO - Got Feature: ['B07D0451', 005, 235405, 582465, '2002-10-25', '2016-11-10', 63.29, 13.24, 64.29, 14.24, -62.94, -12.89, '', ''], size: 52858
#2017-06-10 08:56:28,522 - __main__ - INFO - Got Feature: ['B07D0451', 001, 235405, 582465, '2002-10-25', '2016-11-10', 63.29, 13.24, 64.29, 14.24, -62.94, -12.89, '', ''], size: 60107
#Traceback (most recent call last):
  File "groundwater_timenet/dino.py", line 324, in <module>
    download_hdf5(skip, FILENAME_BASE)
  File "groundwater_timenet/dino.py", line 266, in download_hdf5
    dataset[...] = data
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper (/tmp/pip-huypgcah-build/h5py/_objects.c:2840)
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper (/tmp/pip-huypgcah-build/h5py/_objects.c:2798)
  File "/home/floodgates/.local/lib/python3.5/site-packages/h5py/_hl/dataset.py", line 629, in __setitem__
    for fspace in selection.broadcast(mshape):
  File "/home/floodgates/.local/lib/python3.5/site-packages/h5py/_hl/selections.py", line 299, in broadcast
    raise TypeError("Can't broadcast %s -> %s" % (target_shape, count))
TypeError: Can't broadcast (60107, 2) -> (52713, 2)
```
